name: Build and Deploy to Minikube2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Docker image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build --platform linux/amd64 -t my-python-app .
        kubectl create deployment my-python-app --image=my-python-app
        kubectl expose deployment my-python-app --type=LoadBalancer --port=8080
